name: Deploy to Cloudflare Pages

on: workflow_dispatch

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-command: build-site
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: mv INSERT-ARTIFACT-NAME-HERE dist
      - name: Cloudflare Pages GitHub Action
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 495d6e54a024f90d5ab36bcabd41ab33
          projectName: INSERT-PROJECT-NAME-HERE
          directory: dist
