name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          release-type: node
  publish-package:
    name: Publish package
    needs: release-please
    uses: ./.github/workflows/publish-package.yml
    # Only publish package upon merge of new release
    if: ${{ needs.release-please.outputs.release_created }}
